FROM node:14-slim
WORKDIR /app
# COPY serviceAccountKey.json .
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . ./
EXPOSE 80
CMD ["npm", "start" ]
ENV PORT=8000

# The name of the header that BC webhook will hold the Atraqt token value
ENV WEBHOOK_CUSTOM_HEADER_NAME="Attraqt-Access-Token"

# KONG api url
ENV KONG_URL=""

# CIDP api url http://items-dev.attraqt.io/items or http://items.attraqt.io/items depending on the environment
ENV CIDP_URL=""


ENV KEYCLOAK_URL=""
ENV KEYCLOAK_CLIENT_ID=""
ENV KEYCLOAK_CLIENT_SECRET=""

# If we want to keep track of the failed payload shipping attempts, we need to set this flag to true.
ENV ENABLE_PAYLOAD_LEDGER=false
# If payload ledger is enabled, we need to set the retry interval in miliseconds.
ENV PAYLOAD_LEDGER_RESHIP_TIMEOUT=5000